[2023-01-04T14:47:51.480+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2023-01-04T14:47:44.537084+00:00 [queued]>
[2023-01-04T14:47:51.509+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2023-01-04T14:47:44.537084+00:00 [queued]>
[2023-01-04T14:47:51.511+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T14:47:51.512+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T14:47:51.513+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T14:47:51.544+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard_task> on 2023-01-04 14:47:44.537084+00:00
[2023-01-04T14:47:51.558+0000] {standard_task_runner.py:55} INFO - Started process 1349 to run task
[2023-01-04T14:47:51.566+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'titanic_etl_pipeline', 'create_dashboard_task', 'manual__2023-01-04T14:47:44.537084+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/titanic_etl.py', '--cfg-path', '/tmp/tmpzt370syr']
[2023-01-04T14:47:51.576+0000] {standard_task_runner.py:83} INFO - Job 55: Subtask create_dashboard_task
[2023-01-04T14:47:51.694+0000] {task_command.py:389} INFO - Running <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2023-01-04T14:47:44.537084+00:00 [running]> on host 82367dbeb80f
[2023-01-04T14:47:51.845+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=titanic_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T14:47:44.537084+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T14:47:44.537084+00:00
[2023-01-04T14:47:51.885+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8050/
[2023-01-04T14:47:51.885+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8050/

[2023-01-04T14:47:51.895+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-04T14:47:51.895+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-04T14:47:51.897+0000] {logging_mixin.py:137} WARNING - Address already in use
[2023-01-04T14:47:51.898+0000] {logging_mixin.py:137} WARNING - Port 8050 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2023-01-04T14:47:51.939+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-04T14:47:51.982+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
