[2023-01-04T14:53:04.074+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2023-01-04T14:47:44.537084+00:00 [queued]>
[2023-01-04T14:53:04.096+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2023-01-04T14:47:44.537084+00:00 [queued]>
[2023-01-04T14:53:04.097+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T14:53:04.100+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-01-04T14:53:04.101+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T14:53:04.125+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard_task> on 2023-01-04 14:47:44.537084+00:00
[2023-01-04T14:53:04.139+0000] {standard_task_runner.py:55} INFO - Started process 1998 to run task
[2023-01-04T14:53:04.146+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'titanic_etl_pipeline', 'create_dashboard_task', 'manual__2023-01-04T14:47:44.537084+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/titanic_etl.py', '--cfg-path', '/tmp/tmp2tgy_9k6']
[2023-01-04T14:53:04.161+0000] {standard_task_runner.py:83} INFO - Job 57: Subtask create_dashboard_task
[2023-01-04T14:53:04.319+0000] {task_command.py:389} INFO - Running <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2023-01-04T14:47:44.537084+00:00 [running]> on host 82367dbeb80f
[2023-01-04T14:53:04.457+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=titanic_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T14:47:44.537084+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T14:47:44.537084+00:00
[2023-01-04T14:53:04.509+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8050/
[2023-01-04T14:53:04.509+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8050/

[2023-01-04T14:53:04.526+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-04T14:53:04.529+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-04T14:53:04.530+0000] {logging_mixin.py:137} WARNING - Address already in use
[2023-01-04T14:53:04.531+0000] {logging_mixin.py:137} WARNING - Port 8050 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2023-01-04T14:53:04.560+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-04T14:53:04.594+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
