[2023-01-04T14:46:09.955+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2023-01-04T14:40:49.260155+00:00 [queued]>
[2023-01-04T14:46:09.969+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2023-01-04T14:40:49.260155+00:00 [queued]>
[2023-01-04T14:46:09.970+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T14:46:09.973+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-01-04T14:46:09.975+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T14:46:09.999+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard_task> on 2023-01-04 14:40:49.260155+00:00
[2023-01-04T14:46:10.006+0000] {standard_task_runner.py:55} INFO - Started process 1150 to run task
[2023-01-04T14:46:10.012+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'titanic_etl_pipeline', 'create_dashboard_task', 'manual__2023-01-04T14:40:49.260155+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/titanic_etl.py', '--cfg-path', '/tmp/tmpiwgy21ku']
[2023-01-04T14:46:10.017+0000] {standard_task_runner.py:83} INFO - Job 51: Subtask create_dashboard_task
[2023-01-04T14:46:10.105+0000] {task_command.py:389} INFO - Running <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2023-01-04T14:40:49.260155+00:00 [running]> on host 82367dbeb80f
[2023-01-04T14:46:10.199+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=titanic_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T14:40:49.260155+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T14:40:49.260155+00:00
[2023-01-04T14:46:10.231+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8050/
[2023-01-04T14:46:10.231+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8050/

[2023-01-04T14:46:10.240+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-04T14:46:10.243+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-04T14:46:10.245+0000] {logging_mixin.py:137} WARNING - Address already in use
[2023-01-04T14:46:10.246+0000] {logging_mixin.py:137} WARNING - Port 8050 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2023-01-04T14:46:10.307+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-04T14:46:10.341+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
